CREATE TABLE Users (
  id          VARCHAR(36) PRIMARY KEY,
  name        VARCHAR(255),
  email       VARCHAR(255),
  password    VARCHAR(255),
  createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt   DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Stores (
  id          VARCHAR(36) PRIMARY KEY,
  name        VARCHAR(255),
  userId      VARCHAR(36),
  createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt   DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users (id) ON DELETE CASCADE
);

CREATE TABLE Billboards (
  id          VARCHAR(36) PRIMARY KEY,
  storeId     VARCHAR(36),
  label       VARCHAR(255),
  imageUrl    VARCHAR(255),
  createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt   DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (storeId) REFERENCES Stores (id) ON DELETE CASCADE
);

CREATE TABLE Categories (
  id          VARCHAR(36) PRIMARY KEY,
  storeId     VARCHAR(36),
  billboardId VARCHAR(36),
  name        VARCHAR(255),
  createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt   DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (storeId) REFERENCES Stores (id) ON DELETE CASCADE,
  FOREIGN KEY (billboardId) REFERENCES Billboards (id) ON DELETE CASCADE
);

CREATE TABLE Products (
  id          VARCHAR(36) PRIMARY KEY,
  storeId     VARCHAR(36),
  categoryId  VARCHAR(36),
  name        VARCHAR(255),
  price       DECIMAL(10, 2),
  isFeatured  boolean,
  isArchived  boolean,
  sizeId      VARCHAR(36),
  colorId     VARCHAR(36),
  createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt   DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (storeId) REFERENCES Stores (id) ON DELETE CASCADE,
  FOREIGN KEY (categoryId) REFERENCES Categories (id) ON DELETE CASCADE,
  FOREIGN KEY (sizeId) REFERENCES Sizes (id) ON DELETE CASCADE,
  FOREIGN KEY (colorId) REFERENCES Colors (id) ON DELETE CASCADE
);

CREATE TABLE Orders (
  id        VARCHAR(36) PRIMARY KEY,
  storeId   VARCHAR(36),
  isPaid    boolean,
  phone     VARCHAR(255) DEFAULT "",
  address   VARCHAR(255) DEFAULT "",
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (storeId) REFERENCES Stores (id) ON DELETE CASCADE
);

CREATE TABLE OrderItems (
  id        VARCHAR(36) PRIMARY KEY,
  orderId   VARCHAR(36),
  productId VARCHAR(36),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES Orders (id) ON DELETE CASCADE,
  FOREIGN KEY (productId) REFERENCES Products (id) ON DELETE CASCADE
);

CREATE TABLE Sizes (
  id        VARCHAR(36) PRIMARY KEY,
  storeId   VARCHAR(36),
  name      VARCHAR(255),
  value     VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (storeId) REFERENCES Stores (id) ON DELETE CASCADE
);

CREATE TABLE Colors (
  id        VARCHAR(36) PRIMARY KEY,
  storeId   VARCHAR(36),
  name      VARCHAR(255),
  value     VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (storeId) REFERENCES Stores (id) ON DELETE CASCADE
);

CREATE TABLE Images (
  id        VARCHAR(36) PRIMARY KEY,
  productId VARCHAR(36),
  url       VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (productId) REFERENCES Products (id) ON DELETE CASCADE
);